### PR TITLE
Added Gatekeeper Operator in the catalog

### PR DESCRIPTION
**Pull request by rcarrata**
Added Gatekeeper Operator in the Gitops catalog with following the structure depicted in the guidelines: 

```
tree -L 2
.
├── base
│   ├── instance
│   └── operator
├── overlays
│   └── upstream
└── README.md
```

Included the documentation and tested in OCP4.8.12 (fully working).

### CODE REVIEW

**Comment by pittar** [comment]
Hey @rcarrata , thanks for the contribution!  This is a nice addition to the catalog.
Before we merge this PR, could you please refactor the directory structure to align with the contributing guide, please:
https://github.com/redhat-cop/gitops-catalog/blob/main/CONTRIBUTING.md

You can also use the ACS operator as an example (the "aggregate" directory is purely optional, and only required if you want to deploy the operator and an instance in a single step).
https://github.com/redhat-cop/gitops-catalog/tree/main/advanced-cluster-security-operator

Sorry for the confusion.  We do have a lot of entries that match the format you have used, but we are slowly trying to migrate them over to the new structure.

Thanks!

**Comment by rcarrata** [comment]
hello @pittar. Sure thing! thanks for the tips :) 

I'll modify the structure following the guides that you pointed.

**Comment by pittar** [comment]
@rcarrata Great! When it's ready, set me as a reviewer and I'll merge it as soon as I get a chance.

**Comment by pittar** [comment]
Merging for now, as I'd like to see this operator in the catalog.  Will look at refactoring once it is in main.

**Pull request merged**
