### PR TITLE
New OCS folder structure + 4.8 and eus-46 channels

### PR DESCRIPTION
**Pull request by pittar**
- Updated OCS operator folder structure to match current standards.
- Added `stable-4.8` and `eus-4.6` channels.
- Added the standard `openshift-storage` namespace to base.
- Patch olm label, since the list of provided APIs is different between releases.

### CODE REVIEW

**Comment by gnunn1** [comment]
Looks good, one question should we be providing the annotation `olm.providedAPIs` pre-filled or just omitting it and letting OLM deal with it? I'm mostly going with leaving it blank and letting OLM manage it to reduce complexity but it's not a big deal.

**Comment by pittar** [comment]
@gnunn1 , that's a good suggestion for `olm.providedAPIs`, I didn't realize they would be properly filled in.  If that's the case, and I simply need the `OperatorGroup`, then that makes things much simpler.

I'll give it a try without the `olm.providedAPIs` just to make sure things work the way they should.  Thanks!

**Comment by pittar** [comment]
Removed the `old.providedAPIs` annotation and patch files.

**Comment by gnunn1** [comment]
Looks fine to me!

**Pull request merged**
