### PR TITLE
Rhoda operator

### PR DESCRIPTION
**Pull request by veniceofcode**
Added manifests for Red Hat Openshift Database Access Operator

The same have been working fine when tested manually

### CODE REVIEW

**Comment by pittar** [comment]
Hi @veniceofcode .  Thanks for the contribution.  Can you please remove the `.idea` directory, and update the README.md file to describe the operator that is being installed (right now it's just copy/paste of the ACM README).

**Comment by strangiato** [comment]
I also discussed this with @veniceofcode separately but I would recommend breaking the install.yaml file down into separate files for each component to keep it consistent with the rest of the catalog.

**Comment by pittar** [comment]
@strangiato , good points.  Once those little things are taken care of, it'll be a nice addition.  I will be AFK for about an hour.  I can merge then, or someone else can hit the button once it's ready :)

**Comment by veniceofcode** [comment]
@pittar @strangiato Done, please review, i believe i removed the .idea in one of the commits

**Comment by pittar** [comment]
@veniceofcode - unless there's a caching issue on my end, it still looks like the README describes the Advanced Cluster Management operator, not RHODA.

**Comment by veniceofcode** [comment]
@pittar I think issue was on my side, the commit has not picked up readme file before, i did again now , please check

**Comment by pittar** [comment]
Thanks for the contribution!

**Pull request merged**
