### PR TITLE
AMQ Broker Operator

### PR DESCRIPTION
**Pull request by rmgrimm**
@jstrickl-redhat and I have put together a base set of files for AMQ Broker Operator, including instance components to facilitate different sets of broker configuration.

### CODE REVIEW

**Comment by rmgrimm** [comment]
There is currently a false negative in the lint-manifests job, due to the use of partial Kustomize Components. Components allow referencing resources that are not directly included within the manifest of the component. This "partial" view of a component allows us to make modification regardless of which other component introduced the resource.

For example, the component at `amq-broker-operator/instance/components/certificates/public-ca-truststores/letsencrypt-prod/console-ssl-keystore` expects a pre-existing secret named `console-ssl-keystore` and updates it to use a letsencrypt CA certificates for trust chains. There are multiple options for creating `console-ssl-keystore`, also including the implicit option to manually create the resource in an overlay.

To help resolve this false negative, I've submitted a secondary pull request to skip components that fail a `kustomize build` at #325

**Comment by pittar** [comment]
Will merge this as soon as the @codekow gives the thumbs up changing the linting process.

**Comment by pittar** [comment]
LTGM.  Thanks.

**Comment by rmgrimm** [comment]
I've rebased to pick up the changed script from #325 . I'll fix the lint-yaml errors and then remove draft status.

**Review by pittar — APPROVED** [review]
Great addition.  Thanks!

**Comment by strangiato** [comment]
This is a fantastic piece of work!

As a follow up, I think it would be great if we could add some READMEs for the components that include some details of what each component does.

Take a look at what we did for the gitops operator as an example:

https://github.com/redhat-cop/gitops-catalog/tree/main/openshift-gitops-operator/instance/components/annotation-resource-tracking

**Comment by rmgrimm** [comment]
Yes, I had planned to add documentation/READMEs throughout the amq-broker-operator tree. I haven't been able to dedicate the time to that yet and didn't want to continue holding the whole PR hostage to my time.

Thank you for the link to reference, @strangiato ! As time allows, I'll aim to write additional documentation and follow conventions/styles from that gitops operator in future documentation PRs.

**Pull request merged**
