### PR TITLE
Automate catalog item creation

### PR DESCRIPTION
**Pull request by codekow**
We need a method for dealing with inconsistencies in the repo. Lets use automation to create items.

### CODE REVIEW

**Comment by codekow** [comment]
This may create breaking changes for people who are not using tags or commits.

I thought the best way to get rid of inconsistencies was to script the creation of what everyone is doing manually.

@strangiato Let me know what you might hate about the output. I've refactored a few existing items to show the changes and consistency.

**Comment by adetalhouet** [comment]
Thanks @codekow for this PR. Please address the merge conflict by rebasing on master.

The idea of a script to generate the scaffolding is great. Please add within the main readme how to use the script.

**Comment by codekow** [comment]
> Thanks @codekow for this PR. Please address the merge conflict by rebasing on master.
> 
> The idea of a script to generate the scaffolding is great. Please add within the main readme how to use the script.

I updated the main README.md with how to load the functions and the script itself should output functions to use as an example.

Should be ready to flatten and merge

**Comment by codekow** [comment]
@strangiato @adetalhouet 

Bump?

**Comment by strangiato** [comment]
LGTM after a rebase to fix the conflicts with the wordlist

**Comment by strangiato** [comment]
Sorry for the delay on getting this merged.

**Pull request merged**
