### PR TITLE
Added Group Sync Operator

### PR DESCRIPTION
**Pull request by sabre1041**
Added Group Sync Operator

### CODE REVIEW

**Review by strangiato — CHANGES_REQUESTED** [review]
Can you create an overlay called alpha and include a patch to set the alpha channel?

**Comment by sabre1041** [comment]
@strangiato i can do that. theres only 1 channel though. is this requirement something we would also want to backport for other operators in the catalog too? Some do not follow this convention

Also, should I also correct the validation failure too?

**Comment by sabre1041** [comment]
Looks like validation failure is caused by new v5.1.0 release and [this feature](https://github.com/kubernetes-sigs/kustomize/pull/4949) which throws an error for empty Kustomization files

**Comment by strangiato** [comment]
@sabre1041 I have a PR out here to resolve that:

https://github.com/redhat-cop/gitops-catalog/pull/226

I'm going to go ahead and merge your change without the pass since the other PR just needs a review to merge.

As far as the overlays are concerned I know we have been trying to keep things as standardized as possible.  From my perspective it is always easier to have a single in place from the beginning and add additional overlays later than it is to go from deploying directly from base and possibly breaking a deployment that is referencing the base directly.

I believe that @codekow did a pretty big update a while back to cleanup a huge number of the operator overlays.  He wrote some pretty cool automation that will scaffold the whole thing for us as well if you want to try that out next time.  

If there are any operators that aren't using an overlay feel free to PR the changes or submit an issue for them though!

**Review by strangiato — APPROVED** [review]

**Pull request merged**
