### PR TITLE
Kustomize build test

### PR DESCRIPTION
**Pull request by strangiato**
Add a github action to run a `kustomize build` on any kustomization.yaml or kustomization.yml files in the repo.

The image being used to test leverages kustomize 4.2 which should match the current version of Argo.

This also resolves several existing issues in the repo for items that do not properly build.

Moving forward this will help to insure that all PR's can successfully build.

### CODE REVIEW

**Comment by strangiato** [comment]
@pittar @gnunn1 

Feedback welcome!

My hope was to add a check in that helps make sure that anything in the repo is valid.

There are some pretty big inconsistency issues between different versions of kustomize so `oc apply -k` may not work with all of these so I chose to prioritize the current version supported by Argo (kustomize 4.2).

**Comment by pittar** [comment]
@strangiato this is a great idea, I wish I had thought of it!  

I do have a minor concern about the version of kustomize, though.  Something that was important to us when we created this catalog was being able to simply `oc/kubectl apply -k` a catalog item.  I would also want to make sure that OpenShift GitOps 1.2 is compatible with this version of kustomize out of the box (although, it would seem you've already looked into that).

@gnunn1 @sabre1041 , what are your thoughts?

**Comment by strangiato** [comment]
Yeah, the compatibility issues between kustomize 2.0.3 and 4.2.0 is a huge pain.

The good news is that `kubectl` is finally able to update the version of kustomize built in as of 1.21 and 1.22 is running 4.2.0!

https://github.com/kubernetes-sigs/kustomize#kubectl-integration

If I remember correctly Argo 1.7.x is running kustomize 3.5.x and the latest version of Argo has updated to 4.2.0 (https://github.com/argoproj/argo-cd/pull/6861).  I haven't been able to find a good support matrix for kustomize in Argo so I'm not sure the exact version running in GitOps but my best guess is 4.1.2.

If we wanted to force compatibility with multiple versions we can break this process off and run checks with as many versions as we want as long as there is an image available to run it.

As of right now I am using the following image as my source for kustomize:
https://hub.docker.com/r/nekottyo/kustomize-kubeval

I would love to switch this over to an image from the RH catalog but I wasn't able to find one specifically for kustomize.  `openshift4/ose-cli` might be a good candidate if we switch the test over to use `oc kustomize`.  @sabre1041 any thoughts on that?

I did some quick testing using `oc` to check to see what was currently broken when trying to use everything with oc.

Errors from `oc kustomize` using 4.7.0/1.20.0:
- apicast/overlays/default
- apicast/overlays/prod
- apicast/overlays/stage
- compliance-operator/overlays/demo
- compliance-operator/overlays/scheduled
- compliance-operator/overlays/release-0.1
- cost-management-operator/overlays/default
- cost-management-operator/overlays/example
- grafana-operator/overlays/user-app-example
- acs-operator/overlays/aggregate-minimal
- acs-operator/overlays/aggregate

Issues Summary:
- apicast/overlays is getting a transformation error I think due to the nameSuffix
- compliance-operator is using folders in `resources` instead of `bases`
- cost-management-operator is using folders in `resources` instead of `bases`
- grafana-operator/overlays/user-app-example is using folders in `resources` instead of `bases`
- acs-operator/overlays is using folders in `resources` instead of `bases`

All of the `bases` vs `resources` issues are easy enough to resolve but `bases` was depreciated in 2.1.0.  I think that we could make it part of the standard to always prefer `bases` over just using `resources` for folders to ensure backwards compatibility.

The transformer error would probably take a little more digging to see exactly what it is being used for.  I'm pretty sure that nameSuffix was not supported in 2.0.3 so we would have to remove that to keep it compatible with `oc apply -k`.

**Comment by strangiato** [comment]
Cancelling PR since Andy's PR does the same checks

**Pull request closed without merging**
