### PR TITLE
Create example gitops instance with components

### PR DESCRIPTION
**Pull request by strangiato**
This is an example gitops instance using components to compose the instance based on the idea @gnunn1 talked about in the GitOps CoP.

Feedback welcome on structure, the scope of each the components, or requests for additional components.

### CODE REVIEW

**Comment by strangiato** [comment]
Added a set of patterns for adding custom health checks.  The `patchesStrategicMerge` method replaces the list object entirely so I had to use the `add` method for the merge in order to allow support of multiple health checks from different components.  

It was also complaining about the path for `resourceHealthChecks` not existing in the base so I had to add an empty list in the base, which does diverge the base from the default openshift-gitops instance which I was trying to avoid.

I'm curious if anyone knows a better way to manage patching the lists.

**Comment by strangiato** [comment]
Currently the health checks include the following objects:

* Subscriptions
* InstallPlans
* ImageStreams
* Builds
* ODF StorageSystem

I think that Subscriptions are included in the upstream checks but have been having a hard time validating those.

**Comment by gnunn1** [comment]
Wow this looks great, using components really helps to get the configuration you need without duplication. Fantastic work on this Trevor.

A couple of comments:
- The base has quite a few empty items, are those needed for patching or can they be removed? For example `sharding: {}` under controller
- Do we still need the subscription health check, I think there was some work upstream to fix it?

**Comment by strangiato** [comment]
For the base, I started with a copy of the default CR that is automatically installed by the operator.  The only modification I have made to it was add the empty `resourceHealthChecks: []` object so that the health checks patch wouldn't complain.

I'm not opposed to removing some of the empty objects but I wanted to start from something that was at least close to the defaults provided by the operator.

For the healthChecks I know that the Subscriptions are present upstream here:

https://github.com/argoproj/argo-cd/tree/master/resource_customizations/operators.coreos.com/Subscription

But I haven't been able to verify that they are present in openshift-gitops (this was why I was asking about the resource_customization folder in the gitops slack).  I was hoping to see where in the code openshift-gitops is pulling in the health checks or somewhere in the built image that they are located but I haven't found a good way to validate those other than try to sync something and see if it looks like it uses a health check.

**Comment by strangiato** [comment]
This should be ready to merge once someone gives it an official review.

**Comment by gnunn1** [comment]
A couple of minor thoughts:

- Should there be a default or recommended overlay, basically the rhdp one without the group?

- I'm still 50/50 on whether the argocd cr should be minimized. The reason why is if the operator defaults change (i.e say resources get increased) the cr will override it. On the other hand one could argue that including the defaults provides a stable and predictable experience. @pittar any thoughts?

This still looks great to me, I'm fine with merging it

**Comment by strangiato** [comment]
I went ahead and added a default overlay with a minimal number of modifications.  Basically just leaving the components that I think would be appropriate as a starting point for any vanilla OCP cluster.  I did leave the component for setting up the group but just didn't add any users to it.  Let me know if you think I should remove that though.

I also went ahead and removed some of the empty objects we talked about before like `sharding: {}`.

I'm curious what @pittar's thoughts are on the resources as well.  I can see valid reasoning for both options.

My original thought was to keep the base as close to the default GitOps creates as possible, and over time, if the operator changes what the defaults are, we could simply copy over the latest version of the default instance.  This obviously does require a bit more operational maintenance for the catalog.

By removing the default resources, we do remove the chance that we will need to maintain those specific configurations if the operator does change the defaults in the future, but it does increase the complexity of updating the object in the catalog if other things are changed on the defaults in the future since more analysis will need to be completed for what should stay and what should not be updated in the base.

**Comment by pittar** [comment]
I don't think there's a prefect answer here.  I see both sides of the argument.

I think the issue is the flexibility of "components" in this case.  They need a CR to patch, and the instance that this is intending to patch was created and managed by the OpenShift GitOps Operator.  In such a case, what I do for my own demos is I create a minimal (incomplete) ArgoCD CR that has the few changes I need and use the "ServerSideApply" annotation to have Argo CD merge my changes into the managed instance.  However, i don't believe that will work with this setup of adding components through patches.

That was a long way of saying I don't know :)  However, I do lean towards @strangiato current solution of including the default CR as the base for a few reasons:

1. It's nice and verbose and clearly shows people the more common toggles they can use.
2. It's simple.
3. This catalog shouldn't be directly used for Production purposes!

Yes, it will take some manual work to keep the base up to date if the operator defaults change, but I don't think that should be too onerous.

I think this PR is ready to merge.

**Comment by strangiato** [comment]
Bump for someone to approve this.

**Review by pittar — APPROVED** [review]
Sorry for the delay.  This is a great initiative!  Approved!

**Pull request merged**
