### PR TITLE
update: scripts

### PR DESCRIPTION
**Pull request by codekow**

### CODE REVIEW

**Review by adetalhouet — APPROVED** [review]

**Review by adetalhouet — APPROVED** [review]

**Comment by adetalhouet** [comment]
@codekow I tried to fix the various conflicts, but I guess I can't do it right. Do you mind fixing the outstanding issues? Thanks

**Comment by codekow** [comment]
@adetalhouet I'll take a look. Sorry for the delay

**Comment by codekow** [comment]
@adetalhouet This should be ready to merge now

**Review by adetalhouet — APPROVED** [review]

**Comment by adetalhouet** [comment]
thanks @codekow

**Pull request merged**
