### PR TITLE
Do not assume CRD exists

### PR DESCRIPTION
**Pull request by adetalhouet**
Signed-off-by: Alexis de Talhouët <adetalhouet89@gmail.com>

### CODE REVIEW

**Comment by pittar** [comment]
LGTM.  Will merge once checks complete.

**Comment by adetalhouet** [comment]
@pittar Thanks - and apologies for the churn. I thought I tested this thoroughly before... but as I just setup  a new cluster, I came to notice it was missing the `SkipDryRunOnMissingResource` flag which prevents Argo from synching the app.

**Comment by pittar** [comment]
@adetalhouet  , I've started add that as a "commonAnnotation" in the kustomization file.  That way the CRDs are pretty clean, and it automatically gets applied to all the bases/resources, like this:
https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/aggregate/default/kustomization.yaml#L4

However... good both ways.  There's only 1 CR that needs it in this case, so no need to move it up to the kustomization file.

**Comment by adetalhouet** [comment]
@pittar just noticed I forget it as well in ansible-automation-platform - added in this PR.

**Comment by pittar** [comment]
LGTM (again)

**Pull request merged**
