### PR TITLE
Add More Linting

### PR DESCRIPTION
**Pull request by codekow**
The purpose of this update is to:
- Avoid / Correct spelling errors in Markdown files
- Avoid / Correct shell script issues
- Improve YAML lint See #62

### CODE REVIEW

**Comment by codekow** [comment]
There are a lot of changes. Let me know if you want me to narrow this down into multiple PRs.

**Comment by pittar** [comment]
@strangiato , it looks like this might overlap a bit with your PR.  Sorry I didn't merge it earlier, I was running low on time to look through the Action.

Would you mind taking a look at this?  Does it make sense to merge both PRs, or just this one?

**Comment by strangiato** [comment]
@pittar I would recommend merging mine first and @codekow can rebase if needed.  This change came from a change that @codekow made on another repo that Cory and I have been working on so it should be mostly compatable.

**Comment by pittar** [comment]
Ok, sounds good.  I'll merge your original PR @strangiato , then we can see how it goes after that :)

**Comment by pittar** [comment]
@strangiato PR has been merged.  I see (as expected) that has caused some conflicts now in this repo.  Sorry about that @codekow !

**Comment by codekow** [comment]
@strangiato No worries! I'll wrangle the chaos. Let me resolve the conflicts

**Comment by codekow** [comment]
@pittar @strangiato I have resolved the conflicts and should have all the updates.

**Comment by pittar** [comment]
@strangiato , I'll defer to you on this one.  You know more about this PR than I do. :)

**Comment by strangiato** [comment]
LGTM!

We tested out a broken PR to validate a few things and everything looks good.

**Comment by pittar** [comment]
In that case, LGTM too :)

**Pull request merged**
